## Creating Arrays 

In [23]:
import numpy as np

In [2]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [3]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4])

In [4]:
b = [5,6,7,8]
b

[5, 6, 7, 8]

In [7]:
arr2d = np.array([a,b])
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2d.shape

(2, 4)

In [10]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
B = np.arange(5,50,3)
B

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [14]:
C = np.arange(25).reshape(5,5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
C.sum()

300

In [17]:
X=np.zeros(10)
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
X.dtype

dtype('float64')

In [19]:
y=np.zeros(25).reshape(5,5)
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
z=np.ones([5,5])
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
y1=np.zeros([5,5])
y1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Arrays aritmetic

In [32]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [34]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [36]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [38]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr ** 5

array([[    1,    32,   243,  1024],
       [ 3125,  7776, 16807, 32768]], dtype=int32)

In [40]:
8**5

32768

In [41]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
A.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [44]:
B = np.arange(6).reshape(2,3)
B

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
Bt = B.T
Bt

array([[0, 3],
       [1, 4],
       [2, 5]])

In [47]:
np.dot(B,Bt)

array([[ 5, 14],
       [14, 50]])

In [55]:
X = np.arange(5,55,5).reshape(5,2)
X

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [57]:
Y = np.arange(2,22,2).reshape(2,5)
Y

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [58]:
Z = np.dot(X,Y)
Z

array([[ 130,  160,  190,  220,  250],
       [ 270,  340,  410,  480,  550],
       [ 410,  520,  630,  740,  850],
       [ 550,  700,  850, 1000, 1150],
       [ 690,  880, 1070, 1260, 1450]])

In [61]:
x= np.ones([3,3])
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
y=np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
np.dot(x,y)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

## Array slices are views

In [66]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
a1=A[:10]
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a1[:]=100
a1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [72]:
#numpy array's changes in elements are visible in original array whereas list does not
A

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [74]:
x= list(range(20))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [75]:
x1 = x[:10]
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
x1[0]=100
x1

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [78]:
# orginal X(list) does not contain any changes of sliced elements
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [79]:
A

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [80]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
B=A.copy()
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
B[0]=100
B

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [83]:
#values does not change in copy
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
X=np.arange(25).reshape(5,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
X[0]

array([0, 1, 2, 3, 4])

In [87]:
X[2]

array([10, 11, 12, 13, 14])

In [88]:
X[2][4]

14

In [90]:
X[3][2]

17

In [91]:
X[3][3]

18

In [92]:
X[4][4]

24

In [94]:
X[2:4,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [95]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
X[[1,2,4]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [97]:
X.sum()

300

In [98]:
X[[1,2,4]].sum()

205

In [100]:
X[[1,2,4]].shape

(3, 5)

In [103]:
# keep pressing run, you will get different outputs ie) function of randonm
X=np.random.randint(10)
X

7

In [104]:
x=[]
y=[]
for i in range(10):
    x.append(np.random.randint(10))
    y.append(np.random.randint(10))
x,y

([4, 7, 4, 0, 4, 9, 4, 1, 8, 2], [2, 4, 1, 7, 6, 6, 6, 5, 8, 1])

In [105]:
x= np.array(x)
y=np.array(y)
x,y

(array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2]), array([2, 4, 1, 7, 6, 6, 6, 5, 8, 1]))

In [106]:
np.add(x,y)

array([ 6, 11,  5,  7, 10, 15, 10,  6, 16,  3])

In [107]:
x

array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2])

In [109]:
y

array([2, 4, 1, 7, 6, 6, 6, 5, 8, 1])

In [110]:
np.maximum(x,y)

array([4, 7, 4, 7, 6, 9, 6, 5, 8, 2])

In [111]:
np.minimum(x,y)

array([2, 4, 1, 0, 4, 6, 4, 1, 8, 1])

In [112]:
np.sqrt(np.minimum(x,y))

array([1.41421356, 2.        , 1.        , 0.        , 2.        ,
       2.44948974, 2.        , 1.        , 2.82842712, 1.        ])

In [113]:
x

array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2])

In [114]:
np.square(x)

array([16, 49, 16,  0, 16, 81, 16,  1, 64,  4], dtype=int32)

In [115]:
x

array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2])

In [116]:
y

array([2, 4, 1, 7, 6, 6, 6, 5, 8, 1])

In [117]:
np.divide(x,y)

array([2.        , 1.75      , 4.        , 0.        , 0.66666667,
       1.5       , 0.66666667, 0.2       , 1.        , 2.        ])

In [118]:
#x**y
np.power(x,y)

array([      16,     2401,        4,        0,     4096,   531441,
           4096,        1, 16777216,        2], dtype=int32)

In [119]:
7**4

2401

In [120]:
x,y

(array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2]), array([2, 4, 1, 7, 6, 6, 6, 5, 8, 1]))

In [121]:
np.mod(x,y)

array([0, 3, 0, 0, 4, 3, 4, 1, 0, 0], dtype=int32)

In [122]:
x

array([4, 7, 4, 0, 4, 9, 4, 1, 8, 2])

In [125]:
x.sort()
x

array([0, 1, 2, 4, 4, 4, 4, 7, 8, 9])

In [127]:
y.sort()
y

array([1, 1, 2, 4, 5, 6, 6, 6, 7, 8])

In [129]:
np.unique(x)

array([0, 1, 2, 4, 7, 8, 9])

In [130]:
np.unique(y)

array([1, 2, 4, 5, 6, 7, 8])

In [132]:
x=[]
y=[]
for i in range(10):
    x.append(np.random.randint(10))
    y.append(np.random.randint(10))
x,y

([8, 8, 2, 3, 5, 2, 6, 6, 0, 4], [3, 6, 8, 4, 4, 1, 8, 8, 4, 1])

In [134]:
x=np.array(x)
y=np.array(y)
x,y

(array([8, 8, 2, 3, 5, 2, 6, 6, 0, 4]), array([3, 6, 8, 4, 4, 1, 8, 8, 4, 1]))

In [135]:
# x>y=?
np.greater(x,y)

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [136]:
b=np.greater(x,y)
b

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [137]:
#if the b has all true?
b.all()

False

In [138]:
# if b has any(atleast one) true?
b.any()

True

In [139]:
x

array([8, 8, 2, 3, 5, 2, 6, 6, 0, 4])

In [140]:
y

array([3, 6, 8, 4, 4, 1, 8, 8, 4, 1])

In [141]:
np.equal(x,y)

array([False, False, False, False, False, False, False, False, False,
       False])

# EXERCISE:

## 1) Create a 4X2 integer array and Prints its attributes
 Note: The element must be a type of unsigned int16. And print the following Attributes: –
1)The shape of an array.
 
2)Array dimensions.

3)The Length of each element of the array in bytes.

Expected Output:

[[64392 31655]

[32579     0]

[49248   462]

[    0     0]]

Printing NumPy array Attributes

Array Shape is:  (4, 2)

Array dimensions are  2
 
Length of each element of array in bytes is  2

In [5]:
import numpy as np
firstarray = np.empty([4,2],dtype=np.uint16)
print("Printing Arrays")
print(firstarray)
print("Printing numpy array attributes")
print("1>Array shape is:",firstarray.shape)
print("2>Array dimensions are:",firstarray.ndim)
print("3>Length of each element of array in bytes is",firstarray.itemsize)

Printing Arrays
[[43052   955]
 [35883 27421]
 [60103 59709]
 [10758 51066]]
Printing numpy array attributes
1>Array shape is: (4, 2)
2>Array dimensions are: 2
3>Length of each element of array in bytes is 2


# 2) Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

Expected Output:

Creating 5X2 array using numpy.arange

[[100 110]

 [120 130]
 
 [140 150]
 
 [160 170]
 
 [180 190]]

In [25]:
X=np.arange(100,200,10).reshape(5,2)

print("Creating 5x2 array using numpy.arange")
print(X)

Creating 5x2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


# 3) Following is the provided numPy array. return array of items in the third column from all rows

sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

Expected Output:

Printing Input Array

[[11 22 33]
 
 [44 55 66]
 
 [77 88 99]]


Printing array of items in the third column from all rows

[22 55 88]

In [24]:
samplearray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print("printing input array")
print(samplearray)
X=samplearray[...,1]
print("printing array of items in the second column from all rows")
print(X)

printing input array
[[11 22 33]
 [44 55 66]
 [77 88 99]]
printing array of items in the second column from all rows
[22 55 88]


# 4) Return array of odd rows and even columns from below numpy array

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 

[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

Expected Output:

    Printing Input Array

[[ 3  6  9 12]
 
 [15 18 21 24]
 
 [27 30 33 36]
 
 [39 42 45 48]
 
 [51 54 57 60]]

Printing array of odd rows and even columns

[[ 6 12]
 
 [30 36]
 
 [54 60]]


In [30]:
samplearray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("printing input array")
print(samplearray)
newarray=samplearray[::2,1::2]
print("printing array of odd rows and even columns")
print(newarray)

printing input array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


#  5) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])

arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

Expected Output:

addition of two arrays is 

[[20 39 33]

 [25 25 28]]


Result array after calculating the square root of all elements

[[ 400 1521 1089]
 
 [ 625  625  784]]

In [43]:
arrayone = np.array([[5, 6, 9], [21 ,18, 27]])
arraytwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print("array 1")
print(arrayone)
print("array 2")
print(arraytwo)
X= arrayone+arraytwo
print(X)
Y= np.square(X)
print(Y)



array 1
[[ 5  6  9]
 [21 18 27]]
array 2
[[15 33 24]
 [ 4  7  1]]
[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


## 6: Split the array into four equal-sized sub-arrays

Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then 

Split the array into four equal-sized sub-arrays.

Expected Output:

Creating 8X3 array using numpy.arange

[[10 11 12]

[13 14 15]

[16 17 18]

[19 20 21]

[22 23 24]

[25 26 27]

[28 29 30]

[31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],[13, 14, 15]]), 

array([[16, 17, 18],[19, 20, 21]]), 

array([[22, 23, 24],[25, 26, 27]]), 

array([[28, 29, 30],[31, 32, 33]])]

In [20]:
import numpy as np
X = np.arange(10,34,1).reshape(8,3)
print("\nCreating 8x3 array using numpy arange:\n",newarray)
subarrays=np.split(X,4)
print("\nDividing 8x3 array into 4 sub array:\n",subarrays)


Creating 8x3 array using numpy arange:
 [[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8x3 array into 4 sub array:
 [array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


## Sort following NumPy array

Case 1: Sort array by the second row

Case 2: Sort the array by the second column

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

Expected Output:

Printing Original array

[[34 43 73]

[82 22 12]

[53 94 66]]

Sorting Original array by second row

[[73 43 34]

[12 22 82]

[66 94 53]]

Sorting Original array by second column

[[82 22 12]

[34 43 73]

[53 94 66]]

In [25]:
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by second row")
print(sortArrayByRow)

print("Sorting Original array by second column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]
